version: '2.3'

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_flyway:
    image: flyway/flyway:7.3.0-alpine
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=postgres -connectRetries=15 migrate
    volumes:
    - ../flyway-image/sql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:
    driver: local